import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopping cart project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <html>
      <body className={inter.className}>
        <Providers>
          <Navigation />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
